#!/usr/bin/env ruby
# frozen_string_literal: true

################################################################################
# Copyright 2018 Thomas Hurst <tom@hur.st>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
################################################################################

# https://stackoverflow.com/questions/895929/how-do-i-determine-the-standard-deviation-stddev-of-a-set-of-values
class WelfordStdDev
  def initialize
    @m = 0.0
    @s = 0.0
    @k = 1
  end

  def <<(val)
    tm = @m
    @m += (val - tm) / @k
    @s += (val - tm) * (val - @m)
    @k += 1
  end

  def stddev
    Math.sqrt(@s / (@k - 1))
  end
end

Event = Struct.new(:pidtid, :proc, :time, :type, :call)
CallAvg = Struct.new(:call, :min, :max, :total, :calls, :stddev)
Call = Struct.new(:call, :elapsed)

calls = Hash.new do |h, k|
  h[k] = CallAvg.new(k, Float::INFINITY, 0, 0, 0, WelfordStdDev.new)
end

last_calls = {}

file = ARGV.first || 'ktrace.out'

max_cmd = 0

IO.popen(%w[kdump -HEnsf] + [file]) do |kdump|
  kdump.each_line do |event|
    _, pid, tid, process, time, type, call = event.split(/\s+/, 7)
    id = pid.to_i | (tid.to_i << 32)
    event = Event.new(id, process, time.to_f, type, call)

    case event.type
    when 'CALL'
      last_calls[id] = event
    when 'RET'
      next unless (last_call = last_calls.delete(id))
      fn = event.call.scan(/\S+/).first
      max_cmd = fn.length if max_cmd < fn.length
      c = calls[fn]
      c.calls += 1
      elapsed = event.time - last_call.time
      c.total += elapsed
      c.max = elapsed if elapsed > c.max
      c.min = elapsed if elapsed < c.min
      c.stddev << elapsed
    end
  end
end

fmt = "%#{max_cmd}.#{max_cmd}s: %2.5fs %5d calls | Avg=%.5fs Max=%.5fs Min=%.5fs StdDev=%.5fs\n"

calls.sort_by { |x| x[1].total }.reverse_each do |r|
  c = r[1]
  printf(fmt,
    c.call, c.total, c.calls, c.total / c.calls, c.max, c.min, c.stddev.stddev)
end
